import 'package:flutter/material.dart';
import '../models/cart_item.dart';
import '../models/order_model.dart';
import '../services/order_service.dart';
import '../widgets/menu_card.dart';
import 'cart_screen.dart';
import 'category_menu_screen.dart';

class MobileHomeScreen extends StatefulWidget {
  const MobileHomeScreen({super.key});

  @override
  State<MobileHomeScreen> createState() => _MobileHomeScreenState();
}

class _MobileHomeScreenState extends State<MobileHomeScreen> {
  List<CartItem> cartItems = [];
  bool isSubmitting = false;

  void _openCategoryMenu(
    BuildContext context,
    String category,
    String imagePath,
    Color accentColor,
  ) {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => CategoryMenuScreen(
          categoryName: category,
          heroImagePath: imagePath,
          accentColor: accentColor,
          onAddToCart: (item) {
            setState(() {
              cartItems.add(item);
            });
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text("${item.title} added to cart!"),
                duration: const Duration(milliseconds: 500),
              ),
            );
          },
        ),
      ),
    );
  }

  void _submitOrder() async {
    if (cartItems.isEmpty) return;

    setState(() => isSubmitting = true);

    final total = cartItems.fold(0.0, (sum, item) => sum + item.total);
    final newOrder = OrderModel(
      id: '', // Generated by Appwrite
      items: List.from(cartItems),
      total: total,
      timestamp: DateTime.now(),
      tableNumber: "T-Mobile",
      status: 'pending',
    );

    try {
      await OrderService().createOrder(newOrder);

      setState(() {
        cartItems.clear();
        isSubmitting = false;
      });

      if (mounted) {
        showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: const Text("تم بنجاح! 🎉"),
            content: const Text("وصل الطلب للمطبخ."),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(context),
                child: const Text("موافق"),
              ),
            ],
          ),
        );
      }
    } catch (e) {
      setState(() => isSubmitting = false);
      if (mounted) {
        showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: const Text("خطأ في الإرسال ❌"),
            content: Text("التفاصيل: $e"),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(context),
                child: const Text("حاول مرة أخرى"),
              ),
            ],
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent, // Inherits gradient from parent
      body: SafeArea(
        child: CustomScrollView(
          slivers: [
            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.all(20.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text(
                      "Paris Food",
                      style: TextStyle(
                        fontFamily: 'JotiOne',
                        fontSize: 28,
                        color: Colors.white,
                      ),
                    ),
                    Container(
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(
                        color: Colors.white.withOpacity(0.1),
                        shape: BoxShape.circle,
                      ),
                      child: const Icon(
                        Icons.notifications_none,
                        color: Colors.white,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            SliverPadding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              sliver: SliverGrid(
                gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 2,
                  crossAxisSpacing: 16,
                  mainAxisSpacing: 16,
                  childAspectRatio: 0.85,
                ),
                delegate: SliverChildListDelegate([
                  MenuCard(
                    title: 'BURGER',
                    imagePath: 'assets/burger.png',
                    accentColor: Colors.orange,
                    onTap: () => _openCategoryMenu(
                      context,
                      'BURGER',
                      'assets/burger.png',
                      Colors.orange,
                    ),
                  ),
                  MenuCard(
                    title: 'PIZZA',
                    imagePath: 'assets/pizza.png',
                    accentColor: Colors.red,
                    onTap: () => _openCategoryMenu(
                      context,
                      'PIZZA',
                      'assets/pizza.png',
                      Colors.red,
                    ),
                  ),
                  MenuCard(
                    title: 'TACOS',
                    imagePath: 'assets/Tacos.png',
                    accentColor: Colors.amber,
                    onTap: () => _openCategoryMenu(
                      context,
                      'TACOS',
                      'assets/Tacos.png',
                      Colors.amber,
                    ),
                  ),
                  MenuCard(
                    title: 'BOISSONS',
                    imagePath: 'assets/burger.png',
                    accentColor: Colors.blue,
                    onTap: () => _openCategoryMenu(
                      context,
                      'BOISSONS',
                      'assets/burger.png',
                      Colors.blue,
                    ),
                  ),
                ]),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: cartItems.isNotEmpty
          ? FloatingActionButton.extended(
              onPressed: isSubmitting
                  ? null
                  : () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) => CartPage(
                            cartItems: cartItems,
                            onOrder: _submitOrder,
                          ),
                        ),
                      );
                    },
              backgroundColor: const Color(0xFFF3A402),
              icon: isSubmitting
                  ? const SizedBox(
                      width: 20,
                      height: 20,
                      child: CircularProgressIndicator(color: Colors.black),
                    )
                  : const Icon(Icons.shopping_basket, color: Colors.black),
              label: Text(
                isSubmitting
                    ? "Sending..."
                    : "View Basket (${cartItems.length})",
                style: const TextStyle(
                  color: Colors.black,
                  fontWeight: FontWeight.bold,
                ),
              ),
            )
          : null,
    );
  }
}
